### ISSUE TITLE
Example using webpack / Es2016 modules ??

### ISSUE THREAD

**Issue by iangregsondev** [samme/phaser-sprite-gui#1]
Can't import it using

import * from 'phaser-sprite-gui';

**Comment by samme** [comment]
I'll look into webpack compatibility. You can try:

Use [webpack-contrib/script-loader](https://github.com/webpack-contrib/script-loader) for phaser-sprite-gui and dat.gui; or

[Use a shim](https://webpack.github.io/docs/shimming-modules.html):

- phaser-sprite-gui expects `this` is the global context
- phaser-sprite-gui expects `this.dat` and `this.Phaser`.
- phaser-sprite-gui sets `this.SpriteGUI`

**Comment by iangregsondev** [comment]
Thanks, yes I did try the script-loader but didn't work..

i used  

`import myfile from 'script-loader!../../../../../../../node_modules/phaser-sprite-gui';`

this is the correct path and I have also npm installed the script-loader

In fact, you can see the entries inside my packages.json file

>     "script-loader": "0.7.0",
>     "phaser-sprite-gui": "0.4.5",

I get that it isn't a constructor :-(

**Comment by samme** [comment]
It should work without shimming now.

```javascript
var SpriteGUI = require('phaser-sprite-gui');
```
